# generated by fastapi-codegen:
#   filename:  openapi-specs/openapi.yaml
#   timestamp: 2025-11-04T21:32:34+00:00

from __future__ import annotations

from pydantic import BaseModel, EmailStr, Field, constr


class User(BaseModel):
    id: int = Field(..., example=1)
    name: str = Field(..., example='Иван Иванов')
    email: EmailStr = Field(..., example='ivan@example.com')


class UserCreate(BaseModel):
    name: constr(min_length=1, max_length=100)
    email: EmailStr
